### ISSUE TITLE
Skip generated files.

### ISSUE THREAD

**Issue by bwplotka** [fatih/faillint#10]
Hey :wave: 

Any ideas on how to deal with generated files? How can we easily ignore those without many faillint invocations? 

> /home/bwplotka/Repos/thanos/pkg/store/storepb/types.pb.go:18:13: declaration "Errorf" from package "fmt" shouldn't be used, suggested: "github.com/pkg/errors.{Errorf}"

I tried `find . -type f -name "*.go" | grep -v vendor/ | grep -vE '*.pb.go' | xargs $(FAILLINT) -paths $(FAILLINT_PATHS)` but got: 

```
-: named files must all be in one directory; have ./test/e2e/ and ./test/e2e/e2ethanos/
faillint: error during loading
```

**Comment by fatih** [comment]
Yeah I think this should be done inside faillint. I've added this functionality into Fixmie once. Here is an example how `golint` does it:

https://github.com/golang/lint/commit/a5f4a247366d8fc436941822e14fc3eac7727015

I think we can use this package for that: https://dmitri.shuralyov.com/go/generated

And we can also probably add a file or flag to ignore certain files as well when there is no Generate directive inside the file. We do it now via `--ignore-tests`, but maybe we can add `--ignore-files="pb.go"` or something similar.

**Comment by fatih** [comment]
(some brain dump, didn't looked detailed yet):

think this could be a separate Analyzer so it's pluggable. The Analyzer is pluggable and uses graph inside and you can `require` certain Analyzers. The reason is to make the Analyzers composable. I think a `fatih/generated` analyzer or `fatih/faillint/generated` analyzer could be used as well.

**Comment by fatih** [comment]
I implemented this and tested internally in some of our code base and it work sell. I'm planning to merge it in the morning (PST).
