### ISSUE TITLE
Analyse go files with buildtags

### ISSUE THREAD

**Issue by pracucci** [fatih/faillint#20]
We have some tests with a buildtag `// +build requires_docker` at the beginning of the file and I've just realised these files are skipped by `faillint` and I can't find a way to specify build tags (I also checked a bit the source code). Is there any way to get it working on source files with build tags?

**Comment by pracucci** [comment]
Do you have any input how I could fix this? I'm open to work on it.

**Comment by fatih** [comment]
Hi @pracucci,

Sorry for the late response. The last couple of months were busy/crazy for me and I took it slow. I should have responded earlier. Thanks for pinging back! 

I created this simple file:

```go
// +build requires_docker

package main

import "errors"

func main() {
	_ = errors.New("foo")
}
```

This command works fine:

```
$ faillint -paths errors demo.go
/Users/fatih/Code/demo/demo.go:5:8: package "errors" shouldn't be imported
```

However specifying the package/dir won't work as you said:

```
$ faillint -paths errors .
-: build constraints exclude all Go files in /Users/fatih/Code/demo
faillint: error during loading
```

One way of using build tags is passing the GOFLAGS env:

```
$ GOFLAGS="-tags=requires_docker" faillint -paths errors .
/Users/fatih/Code/demo/demo.go:5:8: package "errors" shouldn't be imported
```

I didn't see a way to pass a set of tags to the build context via the `go/analysis` framework. I'll let you know if I've found something.

**Comment by pracucci** [comment]
Amazing, it works thanks!
