### ISSUE TITLE
Error "could not import C" when using CGO 

### ISSUE THREAD

**Issue by krasi-georgiev** [fatih/faillint#21]
if I run this target without `build` it fails with the error in the title.
https://github.com/arribada/i360/blob/master/Makefile#L108

Here is a github action.
https://github.com/arribada/i360/runs/1800460336?check_suite_focus=true

When I add build as a prerequisite for this target it works fine.

**Comment by krasi-georgiev** [comment]
just tried: `import "C" //lint:ignore faillint CGO import ignore.` and it doesn't fix the issues.

**Comment by fatih** [comment]
Hi @krasi-georgiev 

I'm closing this issue as the provided information is not sufficient. Please provide a minimal working example. The first link you shared gives `404`. 

Thank you

**Comment by krasi-georgiev** [comment]
I had to make the repo private, once I make it public again will ping you
