### ISSUE TITLE
Error `constant  overflow` for `-math.MaxFloat64`

### ISSUE THREAD

**Issue by krasi-georgiev** [fatih/faillint#24]
running `faillint-v1.7.0 -paths "errors=github.com/pkg/errors" ./...`
in [this](https://github.com/cryptoriums/packages/) repo results in the title error.

go version go1.17.2 linux/amd64

Can see the github actions runs for more details.

**Comment by krasi-georgiev** [comment]
ping @fatih

**Comment by fatih** [comment]
This is now fixed with: https://github.com/fatih/faillint/pull/28 It's released with: https://github.com/fatih/faillint/releases/tag/v1.8.0
