### ISSUE TITLE
[Feature Request] Support excluding packages

### ISSUE THREAD

**Issue by dimitarvdimitrov** [fatih/faillint#25]
It would be nice to have a flag to exclude a package from a scan. 

#### Example

```shell
faillint -paths google.golang.org/grpc/status ./pkg/... -exclude ./pkg/server/...
```

instead of having to do 

```shell
faillint -paths google.golang.org/grpc/status ./pkg/log/... ./pkg/metrics/... ./pkg/internal/... # and so on and so forth
```

**Comment by dimitarvdimitrov** [comment]
@fatih I'm happy to work on this, if the proposal sounds reasonable.

**Comment by fatih** [comment]
@dimitarvdimitrov, thanks for the feedback. I'm not sure I want to add this feature. The `faillint` package works like every other Go tool, and it accepts a set of files or a set of packages. It's up to you to decide what you want to pass. As an example, `go vet` also works similarly. There are no flags as I know to ignore or exclude files.  I would suggest using a wrapper (script/faillint) that uses `find` or any other tool to construct the files/packages you want to lint. Let me know if you have any other questions.

**Comment by fatih** [comment]
Btw here are some example on how to filter via `go list` or `find`: https://stackoverflow.com/questions/40531874/how-to-make-go-linters-ignore-vendor

**Comment by dimitarvdimitrov** [comment]
that makes sense. Thank you for explaining.
