### ISSUE TITLE
Ignore vendor dir

### ISSUE THREAD

**Issue by kadern0** [fatih/faillint#3]
Hello,

what would be the recommended approach for ignoring the `vendor` directory while scanning the rest of the project? 

Would this be a possible upcoming feature?

Thanks.

**Comment by fatih** [comment]
The vendor folder should automatically already excluded. Does that not work for you? 

If not you can run it like this:

```
faillint --paths errors $(go list ./... | grep -v /vendor/)
```

Please open an issue with some example data if you still see an issue.
