### ISSUE TITLE
Example of README: As an example, you could enforce the usage of github.com/pkg/errors instead of the errors package.

### ISSUE THREAD

**Issue by guettli** [fatih/faillint#37]
Example of README:

> As an example, you could enforce the usage of github.com/pkg/errors instead of the errors package.

The Github project `github.com/pkg/errors` is archived.

I am new to Go, but maybe today it is the other way around: You want to enforce that the standard errors package get used?

Maybe update the README?

**Comment by fatih** [comment]
Hi @guettli. It doesn't matter if a project is archived. It's a legit example. Until Go releases a version of errors that provides. stacktraces, it's a good example. Even though is archived, plenty of people also use it. I'll reconsider it again in the future of course. Thanks for bringing it up.
