### ISSUE TITLE
Ignore Tests

### ISSUE THREAD

**Issue by mweb** [fatih/faillint#4]
Would it be possible to ignore test files. I had a quick look at the code. I saw a way to disable the test for test packages but could not see how I would achieve this for a single test file.

I'll try to have a better look at the code maybe I can find something there.

**Comment by fatih** [comment]
Can you please give an example on what you mean, what you want and what you see? I'm using  `go/analysis` package which uses the `go/packages` under the hood. I doubt I have access to some knobs (unless we change the tool `go/packages` is calling, which is `go list` right now),

**Comment by mweb** [comment]
For example, I would like to prohibit the use of reflection within a project. But it is ok if we use this for our unit tests. 

I had a quick look at `go/analysis`. I could not find a quick way to limit the files to be analyzed. But I think I can see a way to ignore certain packages or files during the test. For example, I would like to ignore all packages or files that end with _error.

**Comment by fatih** [comment]
This is now fixed with #5
